/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Proyectos;
import implementaciones.FabricaProyectos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.FabricaLogica;

/**
 *
 * @author Paulina Cortez Alamilla.
 */
public class frmProyectosEncontrados extends javax.swing.JFrame {

            Proyectos proyecto;
    
    /**
     * Creates new form frmProyectosEncontrados
     */
    public frmProyectosEncontrados() {
        initComponents();        
        
    }

    protected void abrirProyectosEncontrados(List <Proyectos> proyectos) {
        frmProyectosEncontrados abrir = new frmProyectosEncontrados();
        consultarProyectos = proyectos;
        abrir.setVisible(true);
        mostrarProyectosEncontrados();
    }
    
    public void mostrarProyectosEncontrados() {
        List<Proyectos> list = null;
        

        list = FabricaProyectos.getInstanciaRep().consultarProyectos();
        
        System.out.println(list);

        if (list == null) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado nada");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tbProyectos.getModel();
        int rowCount = model.getRowCount();
        
        
        Object rowData[]=new Object[1];
        for(int i=0; i <list.size();i++){
            rowData[0]=list.get(i);
            model.addRow(rowData);
        }
//        List<Proyectos> proyectos = consultarProyectos;
//        DefaultTableModel modeloTabla = (DefaultTableModel) this.tbProyectos.getModel();
//
//        modeloTabla.setRowCount(0);
//
//        Object[] fila = new Object[1];
//        proyectos.forEach((Proyectos proyecto) -> {
//            fila[0] = proyecto.getCodigo();
//            fila[1] = proyecto.getNombre();
//            fila[2] = proyecto.getAcronimo();
//            fila[3] = proyecto.getProgramaInvestigacion();
//            fila[4] = proyecto.getDesarrolloFinancia();
//            fila[5] = proyecto.getFechaInicio();
//            fila[6] = proyecto.getFechaFinalizacion();
//            //System.out.println(proyectos.get(0));
//            modeloTabla.addRow(fila);
//        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProyectos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proyectos encontrados.");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("Proyectos Encontrados.");

        tbProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proyectos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProyectosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProyectos);

        btnAgregar.setText("Agregar publicación");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        boolean verificacion = FabricaLogica.getInstancia().verificaElementosSeleccionados(tbProyectos);
        
        if(!verificacion){
            mostrarErrorNoSeleccionoProyecto();
        } else {
            frmRegistrarPublicacion registrar = new  frmRegistrarPublicacion(proyecto);
            registrar.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProyectosMouseClicked
        int index = tbProyectos.getSelectedRow();
        proyecto = (Proyectos)tbProyectos.getValueAt(index, 0);
    }//GEN-LAST:event_tbProyectosMouseClicked

    
    private void mostrarErrorNoSeleccionoProyecto(){
        JOptionPane.showMessageDialog(this, "No ha sido seleccionado ningún proyecto.", "Ha ocurrido un error.", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmProyectosEncontrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmProyectosEncontrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmProyectosEncontrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmProyectosEncontrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmProyectosEncontrados().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tbProyectos;
    // End of variables declaration//GEN-END:variables

   List<Proyectos> consultarProyectos;
}
