
package presentacion;

import dominio.Doctor;
import dominio.EnCongreso;
import dominio.EnRevista;
import dominio.NoDoctor;
import dominio.Profesor;
import dominio.Proyectos;
import dominio.Publicaciones;
import dominio.Tipo;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import negocio.FabricaLogica;

/**
 *
 * @author Paulina Cortez Alamilla.
 */
public class frmRegistrarPublicacion extends javax.swing.JFrame {
    Proyectos proyecto;
    List<Profesor> profesoresParticipantes;
    DefaultListModel modeloIntegrantes = new DefaultListModel();
    
    /**
     * Creates new form frmRegistrarPublicacion
     */
    public frmRegistrarPublicacion(Proyectos proyecto) {
        initComponents();
        this.proyecto = proyecto;
        ((JTextComponent) this.fechaFin.getDateEditor()).setEditable(false);
        ((JTextComponent) this.fechaInicio.getDateEditor()).setEditable(false);
        this.fechaInicio.setDate(new Date());
        this.fechaFin.setDate(new Date());
        profesoresParticipantes = new ArrayList();
        listParticipantes.setModel(modeloIntegrantes);
        limpiarTipo();
        setProfesores();        
    }
    
    public void limpiarTipo(){
    this.campo1.setVisible(false);
    this.campo2.setVisible(false);
    this.campo3.setVisible(false);
    this.campo4.setVisible(false);
    this.campo5.setVisible(false);
    this.campo6.setVisible(false);
    this.campo7.setVisible(false);
    this.campo8.setVisible(false);
    this.campo9.setVisible(false);
    this.txtNombre.setVisible(false);
    this.txtEditorialLugar.setVisible(false);
    this.txtVolumenPais.setVisible(false);
    this.txtNumeroEditorial.setVisible(false);
    this.txtPagInicio.setVisible(false);
    this.txtPagFin.setVisible(false);
    this.comboBoxTipo.setVisible(false);
    this.fechaInicio.setVisible(false);
    this.fechaFin.setVisible(false);
    }
    
    public void limpiar(){
        this.txtSecuencia.setText("");
        this.txtTitulo.setText("");    
        this.modeloIntegrantes.clear();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSecuencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoRevista = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        tipoCongreso = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        campo1 = new javax.swing.JLabel();
        campo2 = new javax.swing.JLabel();
        campo3 = new javax.swing.JLabel();
        campo4 = new javax.swing.JLabel();
        campo5 = new javax.swing.JLabel();
        campo6 = new javax.swing.JLabel();
        campo7 = new javax.swing.JLabel();
        txtEditorialLugar = new javax.swing.JTextField();
        txtVolumenPais = new javax.swing.JTextField();
        txtNumeroEditorial = new javax.swing.JTextField();
        txtPagInicio = new javax.swing.JTextField();
        txtPagFin = new javax.swing.JTextField();
        comboBoxTipo = new javax.swing.JComboBox<>();
        campo8 = new javax.swing.JLabel();
        campo9 = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisponibles = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        listParticipantes = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar publicación.");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Publicación.");

        jLabel2.setText("No. Secuencia.");

        jLabel3.setText("Título.");

        jLabel4.setText("Profesores.");

        tipoRevista.setText("Revista");
        tipoRevista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoRevistaMouseClicked(evt);
            }
        });

        jLabel5.setText("Tipo");

        tipoCongreso.setText("Congreso");
        tipoCongreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoCongresoMouseClicked(evt);
            }
        });

        txtNombre.setText("jTextField3");

        campo1.setText("1");

        campo2.setText("2");

        campo3.setText("3");

        campo4.setText("4");

        campo5.setText("5");

        campo6.setText("6");

        campo7.setText("7");

        txtVolumenPais.setText("jTextField6");

        txtNumeroEditorial.setText("jTextField7");

        txtPagInicio.setText("jTextField8");

        txtPagFin.setText("jTextField9");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        campo8.setText("8");

        campo9.setText("9");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Profesor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDisponibles);

        listParticipantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listParticipantes);

        jLabel6.setText("Integrantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTitulo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(tipoRevista)
                                .addGap(18, 18, 18)
                                .addComponent(tipoCongreso))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campo9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 9, Short.MAX_VALUE))
                                    .addComponent(campo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addComponent(txtEditorialLugar)
                                .addComponent(txtVolumenPais)
                                .addComponent(txtNumeroEditorial)
                                .addComponent(txtPagInicio)
                                .addComponent(txtPagFin)
                                .addComponent(comboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(fechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(fechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditorialLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(campo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVolumenPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPagInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPagFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo8)
                            .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoRevista)
                            .addComponent(tipoCongreso)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo9)
                            .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)
                        .addGap(24, 24, 24))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tipoRevistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoRevistaMouseClicked
        mostrarDatosRevista();
    }//GEN-LAST:event_tipoRevistaMouseClicked

    private void tipoCongresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoCongresoMouseClicked
        mostrarDatosCongreso();
    }//GEN-LAST:event_tipoCongresoMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (tipoCongreso.isSelected()) {this.txtPagInicio.setText("1"); this.txtPagFin.setText("2");}
        boolean verificarCampos = FabricaLogica.getInstancia().verificarInformacionAgregar(txtSecuencia.getText(), txtTitulo.getText(), profesoresParticipantes, txtNombre.getText(), txtEditorialLugar.getText(), txtVolumenPais.getText(), txtPagInicio.getText(), txtPagFin.getText());
        boolean verificarNumeric = FabricaLogica.getInstancia().verificarInformacionAgregar(this.txtSecuencia.getText(), tipoRevista.isSelected(), this.txtVolumenPais.getText(), this.txtNumeroEditorial.getText(), this.txtPagInicio.getText(), this.txtPagFin.getText(), this.txtNumeroEditorial.getText());
        boolean verificar = FabricaLogica.getInstancia().verificarInformacionAgregar(tipoCongreso.isSelected(), this.txtSecuencia.getText());
        boolean verificarPublicaciones = FabricaLogica.getInstancia().verificarPublicacion(txtTitulo.getText());
        if(modeloIntegrantes.isEmpty()){
            JOptionPane.showMessageDialog(this,"Se requiere de al menos un profesor","Advertencia",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (tipoRevista.isSelected() || tipoCongreso.isSelected()) {

            if (/*!verificarCampos ||*/ !verificarNumeric || !verificar) {

                mostrarAdvertenciaCamposErroneos();
                return;
            }
            if (!verificarPublicaciones) {
                mostrarMsjErrorPublicacionExistente();
            } else {

                if (this.tipoRevista.isSelected()) {
                    this.agregarRevista();
                    limpiar();
                } else if (this.tipoCongreso.isSelected()) {
                    this.agregarCongreso();
                    limpiar();
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Es necesario seleccionar un tipo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        limpiar();
        limpiarTipo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisponiblesMouseClicked
        int fila= tblDisponibles.getSelectedRow();
        Profesor profesor = (Profesor) tblDisponibles.getValueAt(fila,0);
        agregarProfesorLista(profesor);
    }//GEN-LAST:event_tblDisponiblesMouseClicked

    private boolean agregarProfesorLista(Profesor profesor){  
        try{
        if(modeloIntegrantes.contains(profesor)){
            JOptionPane.showMessageDialog(this, "El profesor seleccionado ya se encuentra dentro de la lista");
            return false;
        }       
        
        modeloIntegrantes.addElement(profesor);
        profesoresParticipantes.add(profesor);
        
        return true;
        }catch(Exception e){
            
        }
        return true;
    }
    
    public void setProfesores(){
        List<Profesor> list = new ArrayList();   

        for(int i = 0; i < proyecto.getProfesores().size(); i++){
            list.add(proyecto.getProfesores().get(i));
        }

        DefaultTableModel model = (DefaultTableModel) tblDisponibles.getModel();
        int rowCount = model.getRowCount();

        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        Object rowData[] = new Object[1];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i);
            model.addRow(rowData);
        }
    }
    
    private void mostrarAdvertenciaCamposErroneos(){
     JOptionPane.showMessageDialog(this, "Algún campo está vacío o con formato incorrecto.", "Error", JOptionPane.ERROR_MESSAGE);
        
    }
    
    private void mostrarMsjErrorPublicacionExistente(){
     JOptionPane.showMessageDialog(this, "Ya existe una publicación con ese título.", "Error", JOptionPane.ERROR_MESSAGE);   
    }
    
    private void agregarRevista(){
        int secuencia = Integer.parseInt(this.txtSecuencia.getText());
        Publicaciones publicaciones = new Publicaciones (secuencia, this.txtTitulo.getText());
        EnRevista revista = new EnRevista(this.txtNombre.getText(), this.txtEditorialLugar.getText(), Integer.parseInt(this.txtVolumenPais.getText()),
        Integer.parseInt(this.txtNumeroEditorial.getText()),Integer.parseInt(this.txtPagInicio.getText()), Integer.parseInt(this.txtPagFin.getText()));
        publicaciones.setTipoPublicacion(revista.getId());
        publicaciones.setIdProyecto(proyecto.getId());
        publicaciones.setProfesores(profesoresParticipantes);
        
        FabricaLogica.getInstancia().registrarPublicacion(publicaciones, revista);
    }
    
    private void agregarCongreso(){
        int secuencia = Integer.parseInt(this.txtSecuencia.getText());
        Publicaciones publicaciones = new Publicaciones (secuencia, this.txtTitulo.getText());
        EnCongreso congreso;
        if(this.comboBoxTipo.getSelectedIndex() == 0){
            congreso = new EnCongreso(Tipo.Nacional, this.txtNombre.getText(),this.fechaInicio.getDate(), this.fechaFin.getDate(),
                   this.txtEditorialLugar.getText(), this.txtVolumenPais.getText(), this.txtNumeroEditorial.getText());
        } else {
             congreso = new EnCongreso(Tipo.Internacional, this.txtNombre.getText(),this.fechaInicio.getDate(), this.fechaFin.getDate(),
                   this.txtEditorialLugar.getText(), this.txtVolumenPais.getText(), this.txtNumeroEditorial.getText());
        }
        
        publicaciones.setTipoPublicacion(congreso.getId());
        FabricaLogica.getInstancia().registrarPublicacion(publicaciones, congreso);
    }
        
    private void mostrarDatosRevista(){
        if (!tipoCongreso.isSelected()){
        this.campo1.setText("Nombre:"); this.campo1.setVisible(true);this.txtNombre.setVisible(true);this.txtNombre.setText("");
        this.campo2.setText("Editorial:"); this.campo2.setVisible(true); this.txtEditorialLugar.setVisible(true); this.txtEditorialLugar.setText("");
        this.campo3.setText("Volumen:"); this.campo3.setVisible(true); this.txtVolumenPais.setVisible(true); this.txtVolumenPais.setText("");
        this.campo4.setText("Número:"); this.campo4.setVisible(true); this.txtNumeroEditorial.setVisible(true);this.txtNumeroEditorial.setText("");
        this.campo5.setText("Pag. Inicio:"); this.campo5.setVisible(true); this.txtPagInicio.setVisible(true); this.txtPagInicio.setText("");
        this.campo6.setText("Pag. Fin:"); this.campo6.setVisible(true); this.txtPagFin.setVisible(true); this.txtPagFin.setText("");
        this.campo7.setText("");this.campo7.setVisible(false);this.comboBoxTipo.setVisible(false);
        this.campo8.setText(""); this.campo8.setVisible(false); this.fechaInicio.setVisible(false);
        this.campo9.setText(""); this.campo9.setVisible(false); this.fechaFin.setVisible(false);
        } else {
            this.tipoRevista.setSelected(false);
             JOptionPane.showMessageDialog(this, "Solamente puede seleccionar un tipo de publicación.", "Advertencia.", JOptionPane.WARNING_MESSAGE);
            }
        }
    
    private void mostrarDatosCongreso() {
        if (!this.tipoRevista.isSelected()){
        this.campo1.setText("Nombre:"); this.campo1.setVisible(true);this.txtNombre.setVisible(true);this.txtNombre.setText("");
        this.campo2.setText("Lugar:"); this.campo2.setVisible(true); this.txtEditorialLugar.setVisible(true); this.txtEditorialLugar.setText("");
        this.campo3.setText("País:"); this.campo3.setVisible(true); this.txtVolumenPais.setVisible(true); this.txtVolumenPais.setText("");
        this.campo4.setText("Editorial:"); this.campo4.setVisible(true); this.txtNumeroEditorial.setVisible(true);this.txtNumeroEditorial.setText("");
        this.campo5.setText(""); this.campo5.setVisible(false); this.txtPagInicio.setVisible(false); this.txtPagInicio.setText("");
        this.campo6.setText(""); this.campo6.setVisible(false); this.txtPagFin.setVisible(false); this.txtPagFin.setText("");
        this.comboBoxTipo.removeAllItems();
        this.comboBoxTipo.addItem("Nacional"); this.comboBoxTipo.addItem("Internacional");
        this.campo7.setText("Tipo:");this.campo7.setVisible(true);this.comboBoxTipo.setVisible(true);
        this.campo8.setText("Fecha inicio:"); this.campo8.setVisible(true); this.fechaInicio.setVisible(true);
        this.campo9.setText("Fecha fin:"); this.campo9.setVisible(true); this.fechaFin.setVisible(true);
        } else {
                this.tipoCongreso.setSelected(false);
                 JOptionPane.showMessageDialog(this, "Solamente puede seleccionar un tipo de publicación.", "Advertencia.", JOptionPane.WARNING_MESSAGE);
            }
    }
    
 
     
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmRegistrarPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmRegistrarPublicacion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel campo1;
    private javax.swing.JLabel campo2;
    private javax.swing.JLabel campo3;
    private javax.swing.JLabel campo4;
    private javax.swing.JLabel campo5;
    private javax.swing.JLabel campo6;
    private javax.swing.JLabel campo7;
    private javax.swing.JLabel campo8;
    private javax.swing.JLabel campo9;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listParticipantes;
    private static javax.swing.JTable tblDisponibles;
    private javax.swing.JCheckBox tipoCongreso;
    private javax.swing.JCheckBox tipoRevista;
    private javax.swing.JTextField txtEditorialLugar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroEditorial;
    private javax.swing.JTextField txtPagFin;
    private javax.swing.JTextField txtPagInicio;
    private javax.swing.JTextField txtSecuencia;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVolumenPais;
    // End of variables declaration//GEN-END:variables

   
}
